### ISSUE TITLE
it's not clear how the submitted field d- get's injected to recaptchaResponse field on the java side

### ISSUE THREAD

**Issue by drormik** [dtrunk90/recaptcha-spring-integration#1]
Hi,
according to the google documentation:

**For web users, a new field (g-recaptcha-response) will be populated in HTML and you can get the user’s response in one of three ways:

   1. **g-recaptcha-response** POST parameter when the user submits the form on your site
      ....**

keeping with that line,  the **recaptchaResponse**   property of the **AbstractRecaptchaForm** class, will only be populated if a user creates another field (preferably hidden) with **name** and **id** of **recaptchaResponse**.

Then, when a user submits the form, use a "**function onSubmit(token)**" (javascript) we have to assign the _**token**_ value and to the **_recaptchaResponse_** form element.(  **document.getElementById("recaptchaResponse").value=token;**  )

without doing the above steps, the token value will never be sent to google

Perhaps this could be added to the documentation

**Comment by dtrunk90** [comment]
The `RecaptchaServletModelAttributeMethodProcessor` should do this for you without adding a hidden input field. You simply have to do the client side as described in the google documentation and configure your mvc manually if you don't use spring boots autoconfiguration feature. Please take a look into `RecaptchaAutoConfiguration`.

**Comment by dtrunk90** [comment]
I just tested with a Spring Boot application and can confirm that it works. You have to annotate your form object with `@Valid` AND `@ModelAttribute` in order to let the `RecaptchaServletModelAttributeMethodProcessor` kicking in. Pls close if it works for you.

**Comment by drormik** [comment]
many thanks
